"""Make scrapped_at nullable

Revision ID: 768b00a85433
Revises: 6ec4618e8e41
Create Date: 2024-06-26 19:06:37.522674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768b00a85433'
down_revision = '6ec4618e8e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('scrapped_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('scrapped_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
